# .github/workflows/publish.yml
name: Publish Node.js Package

on:
  push:
    branches:
      - master
      - alpha
      - beta
      - released

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com/'

      - name: Install dependencies
        run: npm i --legacy-peer-deps=true

      - name: Run build
        run: npm run build

      - name: Pack-up cache
        run: |
          zip -r cache.zip dist

      - name: Upload cache
        uses: actions/cache@v4
        if: |
          github.ref == 'refs/heads/alpha' ||
          github.ref == 'refs/heads/beta' ||
          github.ref == 'refs/heads/released'
        with:
          key: cache-${{ github.run_id }}
          path: cache.zip

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: |
      github.ref == 'refs/heads/alpha' ||
      github.ref == 'refs/heads/beta' ||
      github.ref == 'refs/heads/released'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com/'

      - name: Download cache
        uses: actions/cache@v4
        with:
          key: cache-${{ github.run_id }}
          path: cache.zip

      - name: Extract cache
        run: |
          unzip -o cache.zip

      - name: Check dist
        run: |
          ls -al ./dist

      - name: Install Norantec Toolchain
        run: npm i @open-norantec/toolchain -g --legacy-peer-deps=true

      - name: Release with semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          BRANCH_NAME: ${{ github.ref_name }}
        run: nttc bump --type $BRANCH_NAME --config ./bump.config.json

      - name: Prepare NPMRC
        run: |
          echo "always-auth=true" >> ./.npmrc
          echo "@open-norantec:registry=https://registry.npmjs.org" >> ./.npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ./.npmrc

      - name: Publish package
        run: npm publish
